version: '3.8'
services:
  ipam-ui:
    environment:
      REACT_APP_AZURE_ENV: ${AZURE_ENV}
      REACT_APP_UI_ID: ${UI_APP_ID}
      REACT_APP_ENGINE_ID: ${ENGINE_APP_ID}
      REACT_APP_TENANT_ID: ${TENANT_ID}
    image: azureipam.azurecr.io/ipam-ui:latest
  ipam-engine:
    environment:
      AZURE_ENV: ${AZURE_ENV}
      CLIENT_ID: ${ENGINE_APP_ID}
      CLIENT_SECRET: ${ENGINE_APP_SECRET}
      TENANT_ID: ${TENANT_ID}
      COSMOS_URL: ${COSMOS_URL}
      COSMOS_KEY: ${COSMOS_KEY}
      KEYVAULT_URL: ${KEYVAULT_URL}
    image: azureipam.azurecr.io/ipam-engine:latest
  nginx-proxy:
    image: azureipam.azurecr.io/ipam-lb:latest
    ports:
      - "80:8080"
