ARG BUILD_IMAGE=registry.access.redhat.com/ubi9/nodejs-22
ARG SERVE_IMAGE=registry.access.redhat.com/ubi9/python-311

# Set Production Build Flag
ARG PROD_BUILD=true

# Set Default Port
ARG PORT=8080

FROM $BUILD_IMAGE AS builder

# Production Build Flag
ARG PROD_BUILD

# Disable NPM Update Notifications
ENV NPM_CONFIG_UPDATE_NOTIFIER=false

# Set the Working Directory
WORKDIR /tmp

# Switch to Root User
USER root

# Copy UI Manifests
COPY ./ui/package*.json ./

# Install UI Dependencies
RUN if [ "${PROD_BUILD}" = true ]; then \
  npm ci; \
else \
  npm install; \
fi

# Copy UI Source Code
COPY ./ui/. ./

# Build IPAM UI
RUN npm run build

FROM $SERVE_IMAGE

# Set Production Build Flag
ARG PROD_BUILD

# Port to Listen On
ARG PORT

# Disable PIP Root Warnings
ARG PIP_ROOT_USER_ACTION=ignore

# Disable PIP Upgrade Warnings
ARG PIP_DISABLE_PIP_VERSION_CHECK=1

# Set Environment Variable
ENV PORT=${PORT}

# Set Working Directory
WORKDIR /tmp

# Switch to Root User
USER root

# Disable Subscription Manager DNF Plugin
RUN sed -i s/enabled=./enabled=0/g /etc/dnf/plugins/subscription-manager.conf

# Install OpenSSH and set the password for root to "Docker!"
RUN dnf update -y \
  && dnf install -y openssh-server \
  && echo "root:Docker!" | chpasswd \
  && dnf clean all \
  && rm -rf /var/cache/dnf

# Enable SSH root login with Password Authentication
# RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config

# Copy 'sshd_config File' to /etc/ssh/
COPY sshd_config /etc/ssh/

RUN ssh-keygen -A && mkdir /var/run/sshd

# Set Working Directory
WORKDIR /ipam

# Install Engine Dependencies
COPY ./engine/requirements.txt /code/requirements.txt
COPY ./engine/requirements.lock.txt /code/requirements.lock.txt

# Install Dependencies
RUN if [ "${PROD_BUILD}" = true ]; then \
  pip install --no-cache-dir -r /code/requirements.lock.txt --progress-bar off; \
else \
  pip install --no-cache-dir -r /code/requirements.txt --progress-bar off; \
fi

# Copy Engine Code
COPY ./engine/app ./app
COPY --from=builder /tmp/dist ./dist

# Copy Init Script
COPY ./init.sh .

# Set Script Execute Permissions
RUN chmod +x init.sh
RUN chown -R 1001:0 /ipam
RUN chown -R 1001:0 /etc/profile

# Switch to Standard User
USER 1001

# Expose Ports
EXPOSE $PORT 2222

# Execute Startup Script
ENTRYPOINT exec ./init.sh ${PORT}
