ARG BUILD_IMAGE=node:22-slim
ARG SERVE_IMAGE=python:3.11-slim

# Set Production Build Flag
ARG PROD_BUILD=true

# Set Default Port
ARG PORT=8080

FROM $BUILD_IMAGE AS builder

# Production Build Flag
ARG PROD_BUILD

# Set Debian Frontend Flag
ARG DEBIAN_FRONTEND=noninteractive

# Disable NPM Update Notifications
ENV NPM_CONFIG_UPDATE_NOTIFIER=false

# Set the Working Directory
WORKDIR /tmp

# Copy UI Manifests
COPY ./ui/package*.json ./

# Install UI Dependencies
RUN if [ "${PROD_BUILD}" = true ]; then \
  npm ci; \
else \
  npm install; \
fi

# Copy UI Source Code
COPY ./ui/. ./

# Build IPAM UI
RUN npm run build

FROM $SERVE_IMAGE

# Set Production Build Flag
ARG PROD_BUILD

# Port to Listen On
ARG PORT

# Set Debian Frontend to Non-Interactive
ARG DEBIAN_FRONTEND=noninteractive

# Disable PIP Root Warnings
ARG PIP_ROOT_USER_ACTION=ignore

# Disable PIP Upgrade Warnings
ARG PIP_DISABLE_PIP_VERSION_CHECK=1

# IPAM Version (for OCI Image Label)
ARG IPAM_VERSION=0.0.0

# Set Environment Variable
ENV PORT=${PORT}

# OCI Image Labels
LABEL org.opencontainers.image.title="Azure IPAM" \
      org.opencontainers.image.version="${IPAM_VERSION}" \
      org.opencontainers.image.source="https://github.com/Azure/ipam"

# Set Working Directory
WORKDIR /tmp

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Install OpenSSH and set the password for root to "Docker!"
RUN apt-get update \
  && apt-get install -y --no-install-recommends openssh-server \
  && echo "root:Docker!" | chpasswd \
  && rm -rf /var/lib/apt/lists/*

# Enable SSH root login with Password Authentication
# RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config

# Copy 'sshd_config File' to /etc/ssh/
COPY sshd_config /etc/ssh/

# Set SSH Key Permissions
RUN ssh-keygen -A && mkdir -p /var/run/sshd

# Set Working Directory
WORKDIR /ipam

# Install Engine Dependencies
COPY ./engine/requirements.txt /code/requirements.txt
COPY ./engine/requirements.lock.txt /code/requirements.lock.txt

# Install Dependencies
RUN if [ "${PROD_BUILD}" = true ]; then \
  pip install --no-cache-dir -r /code/requirements.lock.txt --progress-bar off; \
else \
  pip install --no-cache-dir -r /code/requirements.txt --progress-bar off; \
fi

# Copy Engine Code
COPY ./engine/app ./app
COPY --from=builder /tmp/dist ./dist

# Copy Init Script
COPY ./init.sh .

# Set Script Execute Permissions
RUN chmod +x init.sh

# Expose Ports
EXPOSE $PORT 2222

# Execute Startup Script
ENTRYPOINT ["/bin/sh", "-c", "exec ./init.sh ${PORT}"]
