ARG BASE_IMAGE=python:3.11-slim
FROM $BASE_IMAGE

# Set Production Build Flag
ARG PROD_BUILD=true

# Set Default Port
ARG PORT=80

# Set Debian Frontend to Non-Interactive
ARG DEBIAN_FRONTEND=noninteractive

# Set Environment Variable
ENV PORT=${PORT}

# Disable PIP Root Warnings
ENV PIP_ROOT_USER_ACTION=ignore

# Set the Working Directory
WORKDIR /ipam

# Copy Requirements File
COPY ./requirements.txt .
COPY ./requirements.lock.txt .

# Upgrade PIP
RUN pip install --no-cache-dir --upgrade pip --progress-bar off

# Install Dependencies
RUN if [ "${PROD_BUILD}" = true ]; then \
  pip install --no-cache-dir -r ./requirements.lock.txt --progress-bar off; \
else \
  pip install --no-cache-dir -r ./requirements.txt --progress-bar off; \
fi

# Copy Application Scripts & Sources
COPY ./app ./app
COPY ./init.sh .

# Set Script Execute Permissions
RUN chmod +x init.sh

# Expose Port
EXPOSE $PORT

# Execute Startup Script
ENTRYPOINT ["/bin/sh", "-c", "exec ./init.sh ${PORT}"]
