ARG BASE_IMAGE=python:3.9-slim
FROM $BASE_IMAGE

ARG PORT=80

ADD ./requirements.txt $HOME

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

ADD ./app $HOME/app

EXPOSE $PORT

CMD uvicorn "app.main:app" --reload --host "0.0.0.0" --port $PORT
