ARG BASE_IMAGE=registry.access.redhat.com/ubi9/nginx-126
FROM $BASE_IMAGE

# Create File Links
RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log

# Copy NGINX Config
COPY nginx.conf /etc/nginx/nginx.conf

# Run script uses standard ways to run the application
CMD nginx -g "daemon off;"
