ARG BASE_IMAGE=node:22-slim
FROM $BASE_IMAGE

# Set Production Build Flag
ARG PROD_BUILD=true

# Set Default Port
ARG PORT=80

# Set Debian Frontend to Non-Interactive
ARG DEBIAN_FRONTEND=noninteractive

# IPAM Version (for OCI Image Label)
ARG IPAM_VERSION=0.0.0

# Set Environment Variable
ENV PORT=${PORT}

# Disable NPM Update Warnings
ENV NPM_CONFIG_UPDATE_NOTIFIER=false

# OCI Image Labels
LABEL org.opencontainers.image.title="Azure IPAM UI" \
      org.opencontainers.image.version="${IPAM_VERSION}" \
      org.opencontainers.image.source="https://github.com/Azure/ipam"

# Set the Working Directory
WORKDIR /ipam

# Add Application Sources
COPY . .

# Install Dependencies
RUN if [ "${PROD_BUILD}" = true ]; then \
  npm ci; \
else \
  npm install; \
fi

# Build Application
RUN npm run build

# Set Script Execute Permissions
RUN chmod +x init.sh
RUN rm -rf src

# Expose Port
EXPOSE $PORT

# Execute Startup Script
ENTRYPOINT ["/bin/sh", "-c", "exec ./init.sh ${PORT}"]
