ARG BASE_IMAGE=node:16-slim
FROM $BASE_IMAGE

ARG PORT=80

# Add application sources
ADD . $HOME

# Install Dependencies
RUN npm install

# Build Application
RUN npm run build

# Expose Port
EXPOSE $PORT

# Inject ENV Variables & Start Server
CMD npx --yes react-inject-env set && npx --yes http-server -a 0.0.0.0 -P http://localhost? -p $PORT build
