name: Azure IPAM Release Assets

run-name: Azure IPAM Assets Build & Upload

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  assets:
    name: Build & Upload Asset Files to Release
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by a ${{ github.event_name }} event."
      - run: echo "Release Tag - ${{ github.event.release.tag_name }}."

      - name: "Setup NodeJS v22"
        id: setupNode
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22

      - name: "Setup Python v3.11"
        id: setupPython
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.11'

      - name: Checkout Azure IPAM Code
        id: checkoutRepo
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Install NPM Packages
        id: installNpmPackages
        working-directory: ui
        run: |
          npm ci

      - name: Install PIP Packages
        id: installPipPackages
        working-directory: engine
        run: |
          pip install -r requirements.lock.txt --progress-bar off

      - name: "Create Azure IPAM ZIP Asset"
        id: buildZipAsset
        working-directory: tools
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Name ../assets/ -Force
          ./build.ps1 -Path ../assets/ 

      - name: Upload Azure IPAM Release Asset
        id: uploadReleaseAsset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tagName: ${{ github.event.release.tag_name }}
          assetPath: ./assets/ipam.zip
        run: |
          gh release upload "$tagName" "$assetPath"
