# .github/workflows/run-azure-login.yml
name: Run Azure Login with OpenID Connect

on: [push]

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
      
jobs: 
  test:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
        enable-AzPSSession: true

    - name: Install Az module
      run: |
        Install-Module -Name Az -Force -Scope CurrentUser
        Import-Module Az

    - name: Run deploy script
      shell: pwsh
      run: ./deploy/deploy.ps1
    
